
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Generic -  - avr
      The host system is: Linux - 6.8.0-90-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /usr/bin/avr-gcc 
      Build flags: -mmcu=atmega4808;-DF_CPU=20000000UL;-Os;-ffunction-sections;-fdata-sections
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"
      
      The C compiler identification is GNU, found in:
        /home/arch/CLionProjects/dasboot/build-fw/CMakeFiles/3.28.3/CompilerIdC/a.out
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/arch/CLionProjects/dasboot/build-fw/CMakeFiles/CMakeScratch/TryCompile-wvx6n9"
      binary: "/home/arch/CLionProjects/dasboot/build-fw/CMakeFiles/CMakeScratch/TryCompile-wvx6n9"
    cmakeVariables:
      CMAKE_C_FLAGS: "-mmcu=atmega4808 -DF_CPU=20000000UL -Os -ffunction-sections -fdata-sections"
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: "-mmcu=atmega4808 -Wl,--gc-sections"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/arch/CLionProjects/dasboot/build-fw/CMakeFiles/CMakeScratch/TryCompile-wvx6n9'
        
        Run Build Command(s): /usr/bin/ninja -v cmTC_1ac83
        [1/2] /usr/bin/avr-gcc   -mmcu=atmega4808 -DF_CPU=20000000UL -Os -ffunction-sections -fdata-sections    -v -o CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj -c /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Using built-in specs.
        Reading specs from /usr/lib/gcc/avr/7.3.0/device-specs/specs-atmega4808
        rename spec link to old_link
        COLLECT_GCC=/usr/bin/avr-gcc
        Target: avr
        Configured with: ../gcc/configure -v --enable-languages=c,c++ --prefix=/usr/lib --infodir=/usr/share/info --mandir=/usr/share/man --bindir=/usr/bin --libexecdir=/usr/lib --libdir=/usr/lib --enable-shared --with-system-zlib --enable-long-long --enable-nls --without-included-gettext --disable-libssp --disable-libcc1 --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=avr --enable-host-pie ASFLAGS= ASFLAGS_FOR_BUILD= CFLAGS='-g -O2 -ffile-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat  -fcf-protection -fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1' 'CFLAGS_FOR_BUILD=-g -O2' CPPFLAGS='-Wdate-time -D_FORTIFY_SOURCE=2' CPPFLAGS_FOR_BUILD= CXXFLAGS='-g -O2 -ffile-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat  -fcf-protection -fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1' 'CXXFLAGS_FOR_BUILD=-g -O2' DFLAGS=-frelease DFLAGS_FOR_BUILD=-frelease FCFLAGS='-g -O2 -ffile-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -fcf-protection -fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1' 'FCFLAGS_FOR_BUILD=-g -O2' FFLAGS='-g -O2 -ffile-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -fcf-protection -fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1' 'FFLAGS_FOR_BUILD=-g -O2' GCJFLAGS=-fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1 LDFLAGS='-Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl,-z,relro' LDFLAGS_FOR_BUILD= OBJCFLAGS='-g -O2 -ffile-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat  -fcf-protection -fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1' 'OBJCFLAGS_FOR_BUILD=-g -O2' OBJCXXFLAGS='-g -O2 -ffile-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat  -fcf-protection -fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1' 'OBJCXXFLAGS_FOR_BUILD=-g -O2'
        Thread model: single
        gcc version 7.3.0 (GCC) 
        COLLECT_GCC_OPTIONS= '-D' 'F_CPU=20000000UL' '-Os' '-ffunction-sections' '-fdata-sections' '-v' '-o' 'CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj' '-c' '-specs=device-specs/specs-atmega4808' '-mmcu=avrxmega3'
         /usr/lib/gcc/avr/7.3.0/cc1 -quiet -v -imultilib avrxmega3 -D__AVR_ATmega4808__ -D__AVR_DEVICE_NAME__=atmega4808 -D__AVR_DEV_LIB_NAME__=m4808 -D F_CPU=20000000UL /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c -mn-flash=1 -mno-skip-bug -quiet -dumpbase CMakeCCompilerABI.c -mmcu=avrxmega3 -auxbase-strip CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj -Os -version -ffunction-sections -fdata-sections -o /tmp/ccU1EFAm.s
        GNU C11 (GCC) version 7.3.0 (avr)
        	compiled by GNU C version 13.2.0, GMP version 6.3.0, MPFR version 4.2.1, MPC version 1.3.1, isl version none
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        ignoring nonexistent directory "/usr/lib/gcc/avr/7.3.0/../../../avr/sys-include"
        #include "..." search starts here:
        #include <...> search starts here:
         /usr/lib/gcc/avr/7.3.0/include
         /usr/lib/gcc/avr/7.3.0/include-fixed
         /usr/lib/gcc/avr/7.3.0/../../../avr/include
        End of search list.
        GNU C11 (GCC) version 7.3.0 (avr)
        	compiled by GNU C version 13.2.0, GMP version 6.3.0, MPFR version 4.2.1, MPC version 1.3.1, isl version none
        GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
        Compiler executable checksum: d424640f146a9b01cb085bf03b2e9b9d
        COLLECT_GCC_OPTIONS= '-D' 'F_CPU=20000000UL' '-Os' '-ffunction-sections' '-fdata-sections' '-v' '-o' 'CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj' '-c' '-specs=device-specs/specs-atmega4808' '-mmcu=avrxmega3'
         /usr/lib/gcc/avr/7.3.0/../../../avr/bin/as -mmcu=avrxmega3 -mno-skip-bug -o CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj /tmp/ccU1EFAm.s
        COMPILER_PATH=/usr/lib/gcc/avr/7.3.0/:/usr/lib/gcc/avr/7.3.0/:/usr/lib/gcc/avr/:/usr/lib/gcc/avr/7.3.0/:/usr/lib/gcc/avr/:/usr/lib/gcc/avr/7.3.0/../../../avr/bin/
        LIBRARY_PATH=/usr/lib/gcc/avr/7.3.0/avrxmega3/:/usr/lib/gcc/avr/7.3.0/../../../avr/lib/avrxmega3/:/usr/lib/gcc/avr/7.3.0/:/usr/lib/gcc/avr/7.3.0/../../../avr/lib/
        COLLECT_GCC_OPTIONS= '-D' 'F_CPU=20000000UL' '-Os' '-ffunction-sections' '-fdata-sections' '-v' '-o' 'CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj' '-c' '-specs=device-specs/specs-atmega4808' '-mmcu=avrxmega3'
        [2/2] : && /usr/bin/cmake -E rm -f libcmTC_1ac83.a && /usr/bin/avr-ar qc libcmTC_1ac83.a  CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj && /usr/bin/avr-ranlib libcmTC_1ac83.a && :
        
      exitCode: 0
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:127 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Parsed C implicit include dir info: rv=done
        found start of include info
        found start of implicit include info
          add: [/usr/lib/gcc/avr/7.3.0/include]
          add: [/usr/lib/gcc/avr/7.3.0/include-fixed]
          add: [/usr/lib/gcc/avr/7.3.0/../../../avr/include]
        end of search list found
        collapse include dir [/usr/lib/gcc/avr/7.3.0/include] ==> [/usr/lib/gcc/avr/7.3.0/include]
        collapse include dir [/usr/lib/gcc/avr/7.3.0/include-fixed] ==> [/usr/lib/gcc/avr/7.3.0/include-fixed]
        collapse include dir [/usr/lib/gcc/avr/7.3.0/../../../avr/include] ==> [/usr/lib/avr/include]
        implicit include dirs: [/usr/lib/gcc/avr/7.3.0/include;/usr/lib/gcc/avr/7.3.0/include-fixed;/usr/lib/avr/include]
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:159 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Parsed C implicit link information:
        link line regex: [^( *|.*[/\\])(avr-ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\\]+-)?ld|collect2)[^/\\]*( |$)]
        ignore line: [Change Dir: '/home/arch/CLionProjects/dasboot/build-fw/CMakeFiles/CMakeScratch/TryCompile-wvx6n9']
        ignore line: []
        ignore line: [Run Build Command(s): /usr/bin/ninja -v cmTC_1ac83]
        ignore line: [[1/2] /usr/bin/avr-gcc   -mmcu=atmega4808 -DF_CPU=20000000UL -Os -ffunction-sections -fdata-sections    -v -o CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj -c /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c]
        ignore line: [Using built-in specs.]
        ignore line: [Reading specs from /usr/lib/gcc/avr/7.3.0/device-specs/specs-atmega4808]
        ignore line: [rename spec link to old_link]
        ignore line: [COLLECT_GCC=/usr/bin/avr-gcc]
        ignore line: [Target: avr]
        ignore line: [Configured with: ../gcc/configure -v --enable-languages=c c++ --prefix=/usr/lib --infodir=/usr/share/info --mandir=/usr/share/man --bindir=/usr/bin --libexecdir=/usr/lib --libdir=/usr/lib --enable-shared --with-system-zlib --enable-long-long --enable-nls --without-included-gettext --disable-libssp --disable-libcc1 --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=avr --enable-host-pie ASFLAGS= ASFLAGS_FOR_BUILD= CFLAGS='-g -O2 -ffile-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat  -fcf-protection -fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1' 'CFLAGS_FOR_BUILD=-g -O2' CPPFLAGS='-Wdate-time -D_FORTIFY_SOURCE=2' CPPFLAGS_FOR_BUILD= CXXFLAGS='-g -O2 -ffile-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat  -fcf-protection -fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1' 'CXXFLAGS_FOR_BUILD=-g -O2' DFLAGS=-frelease DFLAGS_FOR_BUILD=-frelease FCFLAGS='-g -O2 -ffile-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -fcf-protection -fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1' 'FCFLAGS_FOR_BUILD=-g -O2' FFLAGS='-g -O2 -ffile-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -fcf-protection -fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1' 'FFLAGS_FOR_BUILD=-g -O2' GCJFLAGS=-fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1 LDFLAGS='-Wl -Bsymbolic-functions -flto=auto -ffat-lto-objects -Wl -z relro' LDFLAGS_FOR_BUILD= OBJCFLAGS='-g -O2 -ffile-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat  -fcf-protection -fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1' 'OBJCFLAGS_FOR_BUILD=-g -O2' OBJCXXFLAGS='-g -O2 -ffile-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=. -flto=auto -ffat-lto-objects -fstack-protector-strong -fstack-clash-protection -Wformat  -fcf-protection -fdebug-prefix-map=/build/gcc-avr-TYLliY/gcc-avr-7.3.0+Atmel3.7.0=/usr/src/gcc-avr-1:7.3.0+Atmel3.7.0-1' 'OBJCXXFLAGS_FOR_BUILD=-g -O2']
        ignore line: [Thread model: single]
        ignore line: [gcc version 7.3.0 (GCC) ]
        ignore line: [COLLECT_GCC_OPTIONS= '-D' 'F_CPU=20000000UL' '-Os' '-ffunction-sections' '-fdata-sections' '-v' '-o' 'CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj' '-c' '-specs=device-specs/specs-atmega4808' '-mmcu=avrxmega3']
        ignore line: [ /usr/lib/gcc/avr/7.3.0/cc1 -quiet -v -imultilib avrxmega3 -D__AVR_ATmega4808__ -D__AVR_DEVICE_NAME__=atmega4808 -D__AVR_DEV_LIB_NAME__=m4808 -D F_CPU=20000000UL /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c -mn-flash=1 -mno-skip-bug -quiet -dumpbase CMakeCCompilerABI.c -mmcu=avrxmega3 -auxbase-strip CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj -Os -version -ffunction-sections -fdata-sections -o /tmp/ccU1EFAm.s]
        ignore line: [GNU C11 (GCC) version 7.3.0 (avr)]
        ignore line: [	compiled by GNU C version 13.2.0  GMP version 6.3.0  MPFR version 4.2.1  MPC version 1.3.1  isl version none]
        ignore line: [GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072]
        ignore line: [ignoring nonexistent directory "/usr/lib/gcc/avr/7.3.0/../../../avr/sys-include"]
        ignore line: [#include "..." search starts here:]
        ignore line: [#include <...> search starts here:]
        ignore line: [ /usr/lib/gcc/avr/7.3.0/include]
        ignore line: [ /usr/lib/gcc/avr/7.3.0/include-fixed]
        ignore line: [ /usr/lib/gcc/avr/7.3.0/../../../avr/include]
        ignore line: [End of search list.]
        ignore line: [GNU C11 (GCC) version 7.3.0 (avr)]
        ignore line: [	compiled by GNU C version 13.2.0  GMP version 6.3.0  MPFR version 4.2.1  MPC version 1.3.1  isl version none]
        ignore line: [GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072]
        ignore line: [Compiler executable checksum: d424640f146a9b01cb085bf03b2e9b9d]
        ignore line: [COLLECT_GCC_OPTIONS= '-D' 'F_CPU=20000000UL' '-Os' '-ffunction-sections' '-fdata-sections' '-v' '-o' 'CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj' '-c' '-specs=device-specs/specs-atmega4808' '-mmcu=avrxmega3']
        ignore line: [ /usr/lib/gcc/avr/7.3.0/../../../avr/bin/as -mmcu=avrxmega3 -mno-skip-bug -o CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj /tmp/ccU1EFAm.s]
        ignore line: [COMPILER_PATH=/usr/lib/gcc/avr/7.3.0/:/usr/lib/gcc/avr/7.3.0/:/usr/lib/gcc/avr/:/usr/lib/gcc/avr/7.3.0/:/usr/lib/gcc/avr/:/usr/lib/gcc/avr/7.3.0/../../../avr/bin/]
        ignore line: [LIBRARY_PATH=/usr/lib/gcc/avr/7.3.0/avrxmega3/:/usr/lib/gcc/avr/7.3.0/../../../avr/lib/avrxmega3/:/usr/lib/gcc/avr/7.3.0/:/usr/lib/gcc/avr/7.3.0/../../../avr/lib/]
        ignore line: [COLLECT_GCC_OPTIONS= '-D' 'F_CPU=20000000UL' '-Os' '-ffunction-sections' '-fdata-sections' '-v' '-o' 'CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj' '-c' '-specs=device-specs/specs-atmega4808' '-mmcu=avrxmega3']
        ignore line: [[2/2] : && /usr/bin/cmake -E rm -f libcmTC_1ac83.a && /usr/bin/avr-ar qc libcmTC_1ac83.a  CMakeFiles/cmTC_1ac83.dir/CMakeCCompilerABI.c.obj && /usr/bin/avr-ranlib libcmTC_1ac83.a && :]
        ignore line: []
        ignore line: []
        implicit libs: []
        implicit objs: []
        implicit dirs: []
        implicit fwks: []
      
      
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1131 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineASMCompiler.cmake:131 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" matched "(GNU assembler)|(GCC)|(Free Software Foundation)":
      avr-gcc (GCC) 7.3.0
      Copyright (C) 2017 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
...
